# Generated by Django 3.2.8 on 2021-10-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20211023_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='static/uploads/profile_pictures/default.png', upload_to='static/uploads/profile_pictures'),
        ),
    ]
